-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-11-22 19:32:26 ACDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
-- Capture run of script in file called custorders_schema_output.txt
set echo on
SPOOL mau_schema_output.txt

--Group id: G20
--Group members: Farisha Jamal, Jack Lovett, Virag Kiss



DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE artwork_media CASCADE CONSTRAINTS;

DROP TABLE artwork_style CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibit CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE sale CASCADE CONSTRAINTS;

DROP TABLE status CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE artist (
    artist_code        NUMBER(7) NOT NULL,
    artist_given_name  VARCHAR2(50) NOT NULL,
    artist_family_name VARCHAR2(50) NOT NULL,
    artist_address     VARCHAR2(50) NOT NULL,
    artist_phone       CHAR(10),
    artist_artwork_qty NUMBER(7) NOT NULL,
    artist_recommended NUMBER(7) NOT NULL
);

COMMENT ON COLUMN artist.artist_code IS
    'artist code';

COMMENT ON COLUMN artist.artist_given_name IS
    'artist given name';

COMMENT ON COLUMN artist.artist_family_name IS
    'artist family name';

COMMENT ON COLUMN artist.artist_address IS
    'artist address';

COMMENT ON COLUMN artist.artist_phone IS
    'artist phone number';

COMMENT ON COLUMN artist.artist_artwork_qty IS
    'artists'' number of artwork in stock';

COMMENT ON COLUMN artist.artist_recommended IS
    'artist code';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    artwork_code       NUMBER(7) NOT NULL,
    artwork_no         NUMBER(7) NOT NULL,
    artwork_title      VARCHAR2(50) NOT NULL,
    artwork_date_added DATE NOT NULL,
    artwork_min_price  VARCHAR2(50) NOT NULL,
    artist_code        NUMBER(7) NOT NULL,
    awmedia_id         NUMBER(7) NOT NULL,
    awstyle_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN artwork.artwork_code IS
    'Artwork code (surrogate PK)';

COMMENT ON COLUMN artwork.artwork_no IS
    'artwork number';

COMMENT ON COLUMN artwork.artwork_title IS
    'artwork title';

COMMENT ON COLUMN artwork.artwork_date_added IS
    'artwork accepted date / artwork added to stock date.';

COMMENT ON COLUMN artwork.artwork_min_price IS
    'artwork minimum price';

COMMENT ON COLUMN artwork.artist_code IS
    'artist code';

COMMENT ON COLUMN artwork.awmedia_id IS
    'Artwork style ID';

COMMENT ON COLUMN artwork.awstyle_id IS
    'Artwork style ID';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artwork_code );

ALTER TABLE artwork ADD CONSTRAINT artwork_nk UNIQUE ( artwork_no,
                                                       artist_code );

CREATE TABLE artwork_media (
    awmedia_id   NUMBER(7) NOT NULL,
    awmedia_name VARCHAR2(50) NOT NULL,
    awmedia_desc VARCHAR2(50)
);

COMMENT ON COLUMN artwork_media.awmedia_id IS
    'Artwork style ID';

COMMENT ON COLUMN artwork_media.awmedia_name IS
    'media name';

COMMENT ON COLUMN artwork_media.awmedia_desc IS
    'media description';

ALTER TABLE artwork_media ADD CONSTRAINT media_pk PRIMARY KEY ( awmedia_id );

CREATE TABLE artwork_style (
    awstyle_id   NUMBER(7) NOT NULL,
    awstyle_name VARCHAR2(50) NOT NULL,
    awstyle_desc VARCHAR2(50)
);

COMMENT ON COLUMN artwork_style.awstyle_id IS
    'Artwork style ID';

COMMENT ON COLUMN artwork_style.awstyle_name IS
    'style name';

COMMENT ON COLUMN artwork_style.awstyle_desc IS
    'style description';

ALTER TABLE artwork_style ADD CONSTRAINT style_pk PRIMARY KEY ( awstyle_id );

CREATE TABLE customer (
    customer_id            NUMBER(7) NOT NULL,
    customer_name          VARCHAR2(50) NOT NULL,
    customer_address       VARCHAR2(50) NOT NULL,
    customer_phone         CHAR(10) NOT NULL,
    customer_business_name VARCHAR2(50)
);

COMMENT ON COLUMN customer.customer_id IS
    'customer id';

COMMENT ON COLUMN customer.customer_name IS
    'customer name';

COMMENT ON COLUMN customer.customer_address IS
    'customer address';

COMMENT ON COLUMN customer.customer_phone IS
    'customer phone number';

COMMENT ON COLUMN customer.customer_business_name IS
    'customer''s business';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE exhibit (
    exhibit_id             NUMBER(7) NOT NULL,
    artwork_code           NUMBER(7) NOT NULL,
    gal_id                 NUMBER(7) NOT NULL,
    exhibit_date_start     DATE NOT NULL,
    exhibit_date_end       DATE NOT NULL,
    exhibit_artwork_in_cat VARCHAR2(3) NOT NULL
);

COMMENT ON COLUMN exhibit.exhibit_id IS
    'Exhibit ID';

COMMENT ON COLUMN exhibit.artwork_code IS
    'Artwork code (surrogate PK)';

COMMENT ON COLUMN exhibit.gal_id IS
    'gallery id';

COMMENT ON COLUMN exhibit.exhibit_date_start IS
    'exhibit start date';

COMMENT ON COLUMN exhibit.exhibit_date_end IS
    'exhibit end date';

COMMENT ON COLUMN exhibit.exhibit_artwork_in_cat IS
    'yes/no for if artwork is featured in the display''s catalog.';

ALTER TABLE exhibit ADD CONSTRAINT exhibit_pk PRIMARY KEY ( exhibit_id );

CREATE TABLE gallery (
    gal_id         NUMBER(7) NOT NULL,
    gal_name       VARCHAR2(50) NOT NULL,
    gal_manager    VARCHAR2(50) NOT NULL,
    gal_street     VARCHAR2(50) NOT NULL,
    gal_town       VARCHAR2(50) NOT NULL,
    gal_state      VARCHAR2(3) NOT NULL,
    gal_phone      CHAR(10) NOT NULL,
    gal_commission VARCHAR2(50),
    gal_time_open  VARCHAR2(50) NOT NULL,
    gal_time_close VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN gallery.gal_id IS
    'gallery id';

COMMENT ON COLUMN gallery.gal_name IS
    'gallery name';

COMMENT ON COLUMN gallery.gal_manager IS
    'gallery manager name';

COMMENT ON COLUMN gallery.gal_street IS
    'gallery address - street number and name.';

COMMENT ON COLUMN gallery.gal_town IS
    'gallery address - town';

COMMENT ON COLUMN gallery.gal_state IS
    'gallery address - state';

COMMENT ON COLUMN gallery.gal_phone IS
    'gallery phone number';

COMMENT ON COLUMN gallery.gal_commission IS
    'gallery commission';

COMMENT ON COLUMN gallery.gal_time_open IS
    'opening time of gallery.';

COMMENT ON COLUMN gallery.gal_time_close IS
    'closing time of gallery.';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gal_id );

CREATE TABLE sale (
    sale_id     NUMBER(7) NOT NULL,
    sale_date   DATE NOT NULL,
    sale_price  VARCHAR2(50) NOT NULL,
    customer_id NUMBER(7) NOT NULL,
    exhibit_id  NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'sale id';

COMMENT ON COLUMN sale.sale_date IS
    'date sale was made';

COMMENT ON COLUMN sale.sale_price IS
    'sale price';

COMMENT ON COLUMN sale.customer_id IS
    'customer id';

COMMENT ON COLUMN sale.exhibit_id IS
    'Exhibit ID';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        exhibit_id
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

CREATE TABLE status (
    status_code       NUMBER(7) NOT NULL,
    status_date       DATE NOT NULL,
    status_of_artwork CHAR(50 CHAR) NOT NULL,
    artwork_code      NUMBER(7) NOT NULL
);

COMMENT ON COLUMN status.status_code IS
    'Artwork status code (Surrogate key)';

COMMENT ON COLUMN status.status_date IS
    'date the  status commenced';

COMMENT ON COLUMN status.status_of_artwork IS
    'description of the status';

COMMENT ON COLUMN status.artwork_code IS
    'Artwork code (surrogate PK)';

ALTER TABLE status ADD CONSTRAINT status_pk PRIMARY KEY ( status_code );

ALTER TABLE status
    ADD CONSTRAINT status_nk UNIQUE ( status_date,
                                      status_of_artwork,
                                      artwork_code );

ALTER TABLE artist
    ADD CONSTRAINT artist_artist FOREIGN KEY ( artist_recommended )
        REFERENCES artist ( artist_code );

ALTER TABLE artwork
    ADD CONSTRAINT artist_artwork FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE artwork
    ADD CONSTRAINT artwork_media FOREIGN KEY ( awmedia_id )
        REFERENCES artwork_media ( awmedia_id );

ALTER TABLE status
    ADD CONSTRAINT artwork_status FOREIGN KEY ( artwork_code )
        REFERENCES artwork ( artwork_code );

ALTER TABLE artwork
    ADD CONSTRAINT artwork_style FOREIGN KEY ( awstyle_id )
        REFERENCES artwork_style ( awstyle_id );

ALTER TABLE sale
    ADD CONSTRAINT customer_sale FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE exhibit
    ADD CONSTRAINT exhibit_artwork FOREIGN KEY ( artwork_code )
        REFERENCES artwork ( artwork_code );

ALTER TABLE sale
    ADD CONSTRAINT exhibit_sale FOREIGN KEY ( exhibit_id )
        REFERENCES exhibit ( exhibit_id );

ALTER TABLE exhibit
    ADD CONSTRAINT gallery_exhibit FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             1
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off
